apiVersion: v1
kind: Service
metadata:
  name: tridentity-service
spec:
  type: LoadBalancer           
  selector:
    app: tridentity-backend    # Connects the service to your pods
  ports:
    - protocol: TCP
      port: 80                 # External port exposed
      targetPort: 5500         # Container port in pod